global population; %% population is a global in real version
global k;

k.CLASS_0 = 0;
k.CLASS_1 = 1;
k.NO_CLASS = -1;
k.NO_TREE = -1;
k.NULL = 0;
k.LEAF_NODE = -1;
k.MIN_POPULATION_SIZE = 10;
k.THRESHOLD_ACCURACY = 0.95;
k.NO_MISCLASSIFICATION = 0;

k.BUJUJ_DATASET = 1;
k.PIMA_INDIANS_DIABETES_DATASET = 2;
k.SIMPLE_POP_DATASET = 3;
k.TEMP_DATASET = 4;
k.POSTPROCESS1_DATASET = 5;
k.POSTPROCESS2_DATASET = 6;
k.BUPA_DATASET = 7;
k.STATLOG_HEART_DATASET = 8;
k.HEPATITIS_DATASET = 9;
k.THYROID_DATASET = 10;
k.MUSK_DATASET = 11;
k.WDBC_DATASET = 12;
k.BUPA_ALCOHOL_DATASET = 13;
k.GLASS_DATASET = 14;
k.IONOSPHERE_DATASET = 15;
