function outputDecTreeToFile(dectree, filename)
    fid = fopen(filename, 'w')
    for n = 1:size(dectree)(1)
        fprintf(fid, 'NODE:%d\n',n)       
        fprintf(fid, 'ancestor %d\n', dectree(n).ancestor)
        fprintf(fid, 'class %d\n' , dectree(n).class)
        fprintf(fid, 'costn')
        fprintf(fid, ' %f', dectree(n).costn)
        fprintf(fid, '\ndatapoints')
        fprintf(fid, ' %d', dectree(n).datapoints)
        fprintf(fid, '\ndsId %d\n', dectree(n).dsId)
        fprintf(fid, 'featuresp')
        fprintf(fid, ' %d', dectree(n).featuresp) 
        fprintf(fid, '\nhyperplane')
        fprintf(fid, ' %f', dectree(n).hyperplane)
        fprintf(fid, '\nldesc %d\n', dectree(n).ldesc)
        fprintf(fid, 'numMisClassified %d\n', dectree(n).numMisClassified)
        fprintf(fid, 'rdesc %d\n', dectree(n).rdesc)
    end
    fclose(fid)
end
